### ISSUE TITLE
OSError: [WinError 10014] 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。

### ISSUE THREAD

**Issue by SDchao** [nonebot/nonebot#130]
在参考NoneBot教程中 开始使用一节 时，运行出现以下错误：
```
[2020-01-27 16:20:53,008 nonebot] INFO: Succeeded to import "nonebot.plugins.base"
[2020-01-27 16:20:53,010 nonebot] INFO: Running on 127.0.0.1:8081
Running on http://127.0.0.1:8081 (CTRL + C to quit)
[2020-01-27 16:20:53,018] Running on 127.0.0.1:8081 over http (CTRL + C to quit)
Accept failed on a socket
socket: <asyncio.TransportSocket fd=920, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 8081)>
Traceback (most recent call last):
  File "D:\SDK\Python\lib\asyncio\proactor_events.py", line 801, in loop
    conn, addr = f.result()
  File "D:\SDK\Python\lib\asyncio\windows_events.py", line 808, in _poll
    value = callback(transferred, key, ov)
  File "D:\SDK\Python\lib\asyncio\windows_events.py", line 557, in finish_accept
    return conn, conn.getpeername()
OSError: [WinError 10014] 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
Task exception was never retrieved
future: <Task finished name='Task-7' coro=<IocpProactor.accept.<locals>.accept_coro() done, defined at D:\SDK\Python\lib\asyncio\windows_events.py:559> exception=OSError(10014, '系统检测到在一个调用中 
尝试使用指针参数时的无效指针地址。', None, 10014, None)>
Traceback (most recent call last):
  File "D:\SDK\Python\lib\asyncio\windows_events.py", line 562, in accept_coro
    await future
  File "D:\SDK\Python\lib\asyncio\proactor_events.py", line 801, in loop
    conn, addr = f.result()
  File "D:\SDK\Python\lib\asyncio\windows_events.py", line 808, in _poll
    value = callback(transferred, key, ov)
  File "D:\SDK\Python\lib\asyncio\windows_events.py", line 557, in finish_accept
    return conn, conn.getpeername()
OSError: [WinError 10014] 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
```

以下为bot.py
```
import nonebot

if __name__ == "__main__" :
    nonebot.init()
    nonebot.load_builtin_plugins()
    nonebot.run(host="127.0.0.1", port=8081)
```

以下为CQHTTP配置
```
{
    "host": "[::]",
    "port": 5700,
    "use_http": true,
    "ws_host": "[::]",
    "ws_port": 6700,
    "use_ws": false,
    "ws_reverse_url": "",
    "ws_reverse_api_url": "ws://127.0.0.1:8081/ws/api/",
    "ws_reverse_event_url": "ws://127.0.0.1:8081/ws/event/",
    "ws_reverse_reconnect_interval": 3000,
    "ws_reverse_reconnect_on_code_1000": true,
    "use_ws_reverse": true,
    "post_url": "",
    "access_token": "",
    "secret": "",
    "post_message_format": "string",
    "serve_data_files": false,
    "update_source": "china",
    "update_channel": "stable",
    "auto_check_update": false,
    "auto_perform_update": false,
    "show_log_console": true,
    "log_level": "info"
}
```
CQHTTP  控制台重复显示
```
[2020-01-27 16:22:27.349] [I] [反向WS] 开启反向 WebSocket 客户端（API）成功，开始连接 ws://127.0.0.1:8081/ws/api/
[2020-01-27 16:22:29.355] [W] [反向WS] 反向 WebSocket（API）客户端连接失败或异常断开，将在 3000 毫秒后尝试重连
```

希望可以帮忙解决一下，万分感谢ww

**Comment by SDchao** [comment]
已经降级成为了3.7…运行正常
我等会再安装3.8试试

**Comment by SDchao** [comment]
最近几天换回了Python3.8，仍然有这个问题
aiocqhttp版本为1.2.5
```
[2020-04-18 11:42:07,954 nonebot] INFO: Running on 127.0.0.1:8081
Running on http://127.0.0.1:8081 (CTRL + C to quit)
[2020-04-18 11:42:07,989 nonebot] INFO: Scheduler started
[2020-04-18 11:42:08,008] Running on 127.0.0.1:8081 over http (CTRL + C to quit)
Accept failed on a socket
handle_traceback: Handle created at (most recent call last):
  File "D:\SDK\Python\Python38\lib\site-packages\quart\app.py", line 1621, in run
    loop.run_until_complete(task)
  File "D:\SDK\Python\Python38\lib\asyncio\base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "D:\SDK\Python\Python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "D:\SDK\Python\Python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "D:\SDK\Python\Python38\lib\asyncio\base_events.py", line 1823, in _run_once
    event_list = self._selector.select(timeout)
  File "D:\SDK\Python\Python38\lib\asyncio\windows_events.py", line 430, in select
    self._poll(timeout)
  File "D:\SDK\Python\Python38\lib\asyncio\windows_events.py", line 810, in _poll
    f.set_exception(e)
  File "D:\SDK\Python\Python38\lib\asyncio\windows_events.py", line 83, in set_exception
    super().set_exception(exception)
socket: <asyncio.TransportSocket fd=1016, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 8081)>
Traceback (most recent call last):
  File "D:\SDK\Python\Python38\lib\asyncio\proactor_events.py", line 801, in loop
    conn, addr = f.result()
  File "D:\SDK\Python\Python38\lib\asyncio\windows_events.py", line 808, in _poll
    value = callback(transferred, key, ov)
  File "D:\SDK\Python\Python38\lib\asyncio\windows_events.py", line 557, in finish_accept
    return conn, conn.getpeername()
OSError: [WinError 10014] 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
Task exception was never retrieved
future: <Task finished name='Task-6' coro=<IocpProactor.accept.<locals>.accept_coro() done, defined at D:\SDK\Python\Python38\lib\asyncio\windows_events.py:559> exception=OSError(10014, '系统检测到在一个 
调用中尝试使用指针参数时的无效指针地址。', None, 10014, None) created at D:\SDK\Python\Python38\lib\asyncio\windows_events.py:569>
source_traceback: Object created at (most recent call last):
  File "D:\SDK\Python\Python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\SDK\Python\Python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\Users\Wenta\.vscode\extensions\ms-python.python-2020.3.71659\pythonFiles\lib\python\debugpy\no_wheels\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\Wenta\.vscode\extensions\ms-python.python-2020.3.71659\pythonFiles\lib\python\debugpy\no_wheels\debugpy/..\debugpy\server\cli.py", line 429, in main
    run()
  File "c:\Users\Wenta\.vscode\extensions\ms-python.python-2020.3.71659\pythonFiles\lib\python\debugpy\no_wheels\debugpy/..\debugpy\server\cli.py", line 266, in run_file
    runpy.run_path(options.target, run_name=compat.force_str("__main__"))
  File "D:\SDK\Python\Python38\lib\runpy.py", line 263, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "D:\SDK\Python\Python38\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "D:\SDK\Python\Python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "bot.py", line 11, in <module>
    nonebot.run(host="127.0.0.1", port=8081)
  File "D:\SDK\Python\Python38\lib\site-packages\nonebot\__init__.py", line 105, in run
    get_bot().run(host=host, port=port, *args, **kwargs)
  File "D:\SDK\Python\Python38\lib\site-packages\nonebot\__init__.py", line 54, in run
    super().run(host=host, port=port, *args, **kwargs)
  File "D:\SDK\Python\Python38\lib\site-packages\aiocqhttp\__init__.py", line 206, in run
    self._server_app.run(host=host, port=port, *args, **kwargs)
  File "D:\SDK\Python\Python38\lib\site-packages\quart\app.py", line 1621, in run
    loop.run_until_complete(task)
  File "D:\SDK\Python\Python38\lib\asyncio\base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "D:\SDK\Python\Python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "D:\SDK\Python\Python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "D:\SDK\Python\Python38\lib\asyncio\base_events.py", line 1851, in _run_once
    handle._run()
  File "D:\SDK\Python\Python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "D:\SDK\Python\Python38\lib\asyncio\proactor_events.py", line 817, in loop
    f = self._proactor.accept(sock)
  File "D:\SDK\Python\Python38\lib\asyncio\windows_events.py", line 569, in accept
    tasks.ensure_future(coro, loop=self._loop)
Traceback (most recent call last):
  File "D:\SDK\Python\Python38\lib\asyncio\windows_events.py", line 562, in accept_coro
    await future
  File "D:\SDK\Python\Python38\lib\asyncio\proactor_events.py", line 801, in loop
    conn, addr = f.result()
  File "D:\SDK\Python\Python38\lib\asyncio\windows_events.py", line 808, in _poll
    value = callback(transferred, key, ov)
  File "D:\SDK\Python\Python38\lib\asyncio\windows_events.py", line 557, in finish_accept
    return conn, conn.getpeername()
OSError: [WinError 10014] 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
```

**Comment by mnixry** [comment]
@richardchien 我个人认为这个问题很有可能不属于`nonebot`甚至任何第三方库的问题
而有可能是`Python38`提供的`asyncio`对于`Windows`系统本身的兼容性问题

相关issue #122 

网络上搜索到的相关解决方案为以管理员执行
`netsh winsock reset`
