### ISSUE TITLE
在发送群消息时出现异常

### ISSUE THREAD

**Issue by z6189949** [nonebot/nonebot#203]
@bot.on_message('group')
async def _(event: Event):
        message = TklToMine(event.message)
        # await bot.send_group_msg(group_id=1*****2, message=message)
        await bot.send_msg(message_type='group',group_id=10*****2,message=message)
        return
这里是代码 使用两种发送群消息的方式都抛出异常，更换电脑，ip，账号 也均会抛出异常，但如果私聊机器人，一切正常，可以正常执行代码片段，以下是异常详情
Task exception was never retrieved
future: <Task finished coro=<CQHttp._handle_event_with_response() done, defined at C:\Python\Python37\lib\site-packages\aiocqhttp\__init__.py:464> exception=<ActionFailed, retcode=100>>
Traceback (most recent call last):
  File "C:\Python\Python37\lib\site-packages\aiocqhttp\__init__.py", line 466, in _handle_event_with_response
    response = await self._handle_event(payload)
  File "C:\Python\Python37\lib\site-packages\aiocqhttp\__init__.py", line 460, in _handle_event
    await self._bus.emit(event_name, ev)))
  File "C:\Python\Python37\lib\site-packages\aiocqhttp\bus.py", line 35, in emit
    results += await asyncio.gather(*coros)
  File "C:/Users/admin/PycharmProjects/example/Tb_yhj/qBot.py", line 28, in _
    await bot.send_msg(message_type='group',group_id=1098715042,message=message)
  File "C:\Python\Python37\lib\site-packages\aiocqhttp\__init__.py", line 219, in call_action
    return await self._api.call_action(action=action, **params)
  File "C:\Python\Python37\lib\site-packages\aiocqhttp\api_impl.py", line 186, in call_action
    result = await self._wsr_api.call_action(action, **params)
  File "C:\Python\Python37\lib\site-packages\aiocqhttp\api_impl.py", line 162, in call_action
    await ResultStore.fetch(seq, self._timeout_sec))
  File "C:\Python\Python37\lib\site-packages\aiocqhttp\api_impl.py", line 51, in _handle_api_result
    raise ActionFailed(retcode=result.get('retcode'))
aiocqhttp.exceptions.ActionFailed: <ActionFailed, retcode=100>
请问这个如何解决

**Comment by yanyongyu** [comment]
action failed查看酷q日志错误原因，确认一下group_id是否正确
