### ISSUE TITLE
运行`nb run`命令后直接抛出`cannot import name 'WebSocketSetup' from 'nonebot.drivers' `

### ISSUE THREAD

**Issue by MasterYuan418** [nonebot/nonebot#288]
**问题描述**
运行'nb run'命令后直接抛出如下错误：
ImportError: cannot import name 'WebSocketSetup' from 'nonebot.drivers' (/home/ubuntu/.local/lib/python3.8/site-packages/nonebot/drivers/__init__.py)`，已经安装适配器。
![图片](https://user-images.githubusercontent.com/58651976/150980279-ce90ebc1-d0d6-46cc-9d68-695f77efefca.png)
**复现方法**
在Ubuntu 20.4LTS(amd64)中，直接运行nb run

**期望的行为**
正常运行

**日志信息**
```python
NameError: name 'Bot' is not defined
01-25 20:45:59 [WARNING] nonebot | Unknown ForwardRef["Event"] for parameter event
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 19, in run_bot
    module = importlib.import_module(module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/bots/ddbot/./bot.py", line 6, in <module>
    from nonebot.adapters.cqhttp import Bot as CQHTTPBot
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nonebot/adapters/cqhttp/__init__.py", line 14, in <module>
    from .permission import *
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nonebot/adapters/cqhttp/permission.py", line 74, in <module>
    GROUP_ADMIN = Permission(_group_admin)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nonebot/permission.py", line 68, in __init__
    self.checkers: Set[Dependent[bool]] = set(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nonebot/permission.py", line 71, in <genexpr>
    else Dependent[bool].parse(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 114, in parse
    signature = get_typed_signature(call)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nonebot/dependencies/utils.py", line 11, in get_typed_signature
    typed_params = [
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nonebot/dependencies/utils.py", line 16, in <listcomp>
    annotation=get_typed_annotation(param, globalns),
> File "/home/ubuntu/.local/lib/python3.8/site-packages/nonebot/dependencies/utils.py", line 29, in get_typed_annotation
    annotation = evaluate_forwardref(annotation, globalns, globalns)
  File "pydantic/typing.py", line 63, in pydantic.typing.evaluate_forwardref
    return type_._evaluate(globalns, localns)
  File "/usr/lib/python3.8/typing.py", line 518, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Event' is not defined
01-25 20:46:00 [WARNING] nonebot | Unknown ForwardRef["Bot"] for parameter bot
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 19, in run_bot
    module = importlib.import_module(module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/bots/ddbot/./bot.py", line 6, in <module>
    from nonebot.adapters.cqhttp import Bot as CQHTTPBot
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nonebot/adapters/cqhttp/__init__.py", line 14, in <module>
    from .permission import *
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nonebot/adapters/cqhttp/permission.py", line 78, in <module>
    GROUP_OWNER = Permission(_group_owner)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nonebot/permission.py", line 68, in __init__
    self.checkers: Set[Dependent[bool]] = set(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nonebot/permission.py", line 71, in <genexpr>
    else Dependent[bool].parse(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 114, in parse
    signature = get_typed_signature(call)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nonebot/dependencies/utils.py", line 11, in get_typed_signature
    typed_params = [
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nonebot/dependencies/utils.py", line 16, in <listcomp>
    annotation=get_typed_annotation(param, globalns),
> File "/home/ubuntu/.local/lib/python3.8/site-packages/nonebot/dependencies/utils.py", line 29, in get_typed_annotation
    annotation = evaluate_forwardref(annotation, globalns, globalns)
  File "pydantic/typing.py", line 63, in pydantic.typing.evaluate_forwardref
    return type_._evaluate(globalns, localns)
  File "/usr/lib/python3.8/typing.py", line 518, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Bot' is not defined
01-25 20:46:00 [WARNING] nonebot | Unknown ForwardRef["Event"] for parameter event
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 19, in run_bot
    module = importlib.import_module(module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/bots/ddbot/./bot.py", line 6, in <module>
    from nonebot.adapters.cqhttp import Bot as CQHTTPBot
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nonebot/adapters/cqhttp/__init__.py", line 14, in <module>
    from .permission import *
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nonebot/adapters/cqhttp/permission.py", line 78, in <module>
    GROUP_OWNER = Permission(_group_owner)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nonebot/permission.py", line 68, in __init__
    self.checkers: Set[Dependent[bool]] = set(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nonebot/permission.py", line 71, in <genexpr>
    else Dependent[bool].parse(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 114, in parse
    signature = get_typed_signature(call)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nonebot/dependencies/utils.py", line 11, in get_typed_signature
    typed_params = [
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nonebot/dependencies/utils.py", line 16, in <listcomp>
    annotation=get_typed_annotation(param, globalns),
> File "/home/ubuntu/.local/lib/python3.8/site-packages/nonebot/dependencies/utils.py", line 29, in get_typed_annotation
    annotation = evaluate_forwardref(annotation, globalns, globalns)
  File "pydantic/typing.py", line 63, in pydantic.typing.evaluate_forwardref
    return type_._evaluate(globalns, localns)
  File "/usr/lib/python3.8/typing.py", line 518, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Event' is not defined
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 19, in run_bot
    module = importlib.import_module(module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/bots/ddbot/./bot.py", line 6, in <module>
    from nonebot.adapters.cqhttp import Bot as CQHTTPBot
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nonebot/adapters/cqhttp/__init__.py", line 15, in <module>
    from .bot import Bot as Bot
  File "/home/ubuntu/.local/lib/python3.8/site-packages/nonebot/adapters/cqhttp/bot.py", line 14, in <module>
    from nonebot.drivers import Driver, ForwardDriver, WebSocketSetup
ImportError: cannot import name 'WebSocketSetup' from 'nonebot.drivers' (/home/ubuntu/.local/lib/python3.8/site-packages/nonebot/drivers/__init__.py)
```

**相关代码**
```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import nonebot
# from nonebot.adapters.onebot.v11 import Adapter as ONEBOT_V11Adapter
from nonebot.adapters.cqhttp import Bot as CQHTTPBot
nonebot.init()
app = nonebot.get_asgi()
driver = nonebot.get_driver()
# driver.register_adapter(ONEBOT_V11Adapter)
driver.register_adapter("cqhttp", CQHTTPBot)
nonebot.load_builtin_plugins()
nonebot.load_plugins("ddbot/plugins")
if __name__ == "__main__":
    nonebot.logger.warning("Always use `nb run` to start the bot instead of manually running!")
    nonebot.run(app="__mp_main__:app")

```

**运行环境**
 - 操作系统：Ubuntu 20.04LTS
 - OneBot（CQHTTP）实现及版本：go-cqhttp，版本1.0.0~beta8-fix2
 - NoneBot 版本：2.0.0b1
 - aiocqhttp 版本：1.4.2
 - Python 版本：3.8.10

**Comment by mnixry** [comment]
NoneBot 2.0.0b1 版本包含了一些不兼容更新, 你现在正在使用的是旧版的写法
请参考 https://github.com/nonebot/discussions/discussions/74 对您的项目进行迁移
