### ISSUE TITLE
启动时遇到ImportError

### ISSUE THREAD

**Issue by WhitePaper233** [nonebot/nonebot#296]
**问题描述**
启动时遇到ImportError

**复现方法**
使用 `python3.9 Chino.py` 启动机器人

**期望的行为**
正常启动

**日志信息**
```bash
❯ python3.9 Chino.py
Traceback (most recent call last):
  File "/home/homeserver/QQBot/Potato/Chino/Chino.py", line 3, in <module>
    from utils.__main__ import Chino
  File "/home/homeserver/QQBot/Potato/Chino/utils/__main__.py", line 4, in <module>
    import nonebot
  File "/home/homeserver/.local/lib/python3.9/site-packages/nonebot/__init__.py", line 140, in <module>
    from .command import CommandSession, CommandGroup
  File "/home/homeserver/.local/lib/python3.9/site-packages/nonebot/command/__init__.py", line 930, in <module>
    from nonebot.command.group import CommandGroup
  File "/home/homeserver/.local/lib/python3.9/site-packages/nonebot/command/group.py", line 3, in <module>
    from nonebot.plugin import on_command
  File "/home/homeserver/.local/lib/python3.9/site-packages/nonebot/plugin/__init__.py", line 45, in <module>
    from .on import on as on
  File "/home/homeserver/.local/lib/python3.9/site-packages/nonebot/plugin/on.py", line 13, in <module>
    from nonebot.matcher import Matcher
  File "/home/homeserver/.local/lib/python3.9/site-packages/nonebot/matcher.py", line 8, in <module>
    from nonebot.internal.matcher import Matcher as Matcher
  File "/home/homeserver/.local/lib/python3.9/site-packages/nonebot/internal/matcher.py", line 20, in <module>
    from nonebot.dependencies import Dependent
  File "/home/homeserver/.local/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 18, in <module>
    from nonebot.utils import run_sync, is_coroutine_callable
  File "/home/homeserver/.local/lib/python3.9/site-packages/nonebot/utils.py", line 33, in <module>
    from nonebot.typing import overrides
ImportError: cannot import name 'overrides' from 'nonebot.typing' (/home/homeserver/.local/lib/python3.9/site-packages/nonebot/typing.py)
```

**相关代码**
```python
# -*- coding: utf-8 -*-
import os

import nonebot

from utils import config


class Chino:
    @staticmethod
    def run():
        nonebot.init(config)
        nonebot.log.logger.info(f'Chino Bot is running at PID: {os.getpid()}')
        nonebot.load_plugins('./plugins', 'plugins')
        nonebot.run()
```

**运行环境**
 - 操作系统：CentOS 8
 - OneBot（CQHTTP）实现及版本：1.0.0-rc1
 - NoneBot 版本：1.9.1
 - aiocqhttp 版本：1.4.2
 - Python 版本：3.9.9

**Comment by WhitePaper233** [comment]
同样的操作在Windows下可用

**Comment by mnixry** [comment]
混装了nonebot1和nonebot2, 请卸载nonebot2之后重新安装nonebot1
