### ISSUE TITLE
m1 运行报错cannot import name 'escape' from 'jinja2'

### ISSUE THREAD

**Issue by 2270057439** [nonebot/nonebot#297]
**问题描述**
最小实例
```python3
import nonebot

if __name__ == '__main__':
    nonebot.init()
    nonebot.load_builtin_plugins()
    nonebot.run(host='127.0.0.1', port=8080)
```
执行`python3 bot.py`时报错：
```python3
Traceback (most recent call last):
  File "/Users/pebble/Documents/OtherApp/go-cqhttp/code/bot.py", line 1, in <module>
    import nonebot
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/nonebot/__init__.py", line 7, in <module>
    import aiocqhttp
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/aiocqhttp/__init__.py", line 19, in <module>
    from quart import Quart, request, abort, jsonify, websocket, Response
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/quart/__init__.py", line 3, in <module>
    from jinja2 import escape, Markup
ImportError: cannot import name 'escape' from 'jinja2' (/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jinja2/__init__.py)
```

**复现方法**
最小实例

**期望的行为**
期望正常运行

**日志信息**
请附上 NoneBot 和 OneBot（CQHTTP）实现的运行日志（可截图或直接贴文本）。
```python3
Traceback (most recent call last):
  File "/Users/pebble/Documents/Code/PyCharm/BotCode/nonebotv1/awesome-bot/bot.py", line 1, in <module>
    import nonebot
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/nonebot/__init__.py", line 7, in <module>
    import aiocqhttp
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/aiocqhttp/__init__.py", line 19, in <module>
    from quart import Quart, request, abort, jsonify, websocket, Response
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/quart/__init__.py", line 3, in <module>
    from jinja2 import escape, Markup
ImportError: cannot import name 'escape' from 'jinja2' (/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jinja2/__init__.py)

```

**相关代码**
如上描述

**运行环境**
 - 操作系统：MacBookAir M1 macOS Monterey 版本12.3.1 
 - OneBot（CQHTTP）实现及版本：N/N
 - NoneBot 版本：nonebot 1.9.1
 - aiocqhttp 版本：1.4.2
 - Python 版本：Python 3.9.9，pip3 22.0.4，escape 1.1，，Jinja2 3.1.1

**Comment by 2270057439** [comment]
按照`https://github.com/pallets/flask/issues/4494`的操作
`Jinja2==3.0.3 Flask==1.1.2`
和部分反馈描述的一致,出现:
```python3
ModuleNotFoundError: No module named 'werkzeug.useragents'
```

**Comment by cleoold** [comment]
I'll try the newest quart later

**Comment by yanyongyu** [comment]
只需要降级jinja2至3.0.3即可，无需操作flask版本

**Comment by 2270057439** [comment]
> 只需要降级jinja2至3.0.3即可，无需操作flask版本
仍然报错.
```python3
pip3 install jinja2==3.0.3
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
Requirement already satisfied: jinja2==3.0.3 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (3.0.3)
Requirement already satisfied: MarkupSafe>=2.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from jinja2==3.0.3) (2.1.1)
```

```python3
python3 /Users/pebble/Documents/Code/PyCharm/BotCode/nonebotv1/awesome-bot/bot.py
Traceback (most recent call last):
  File "/Users/pebble/Documents/Code/PyCharm/BotCode/nonebotv1/awesome-bot/bot.py", line 1, in <module>
    import nonebot
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/nonebot/__init__.py", line 7, in <module>
    import aiocqhttp
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/aiocqhttp/__init__.py", line 19, in <module>
    from quart import Quart, request, abort, jsonify, websocket, Response
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/quart/__init__.py", line 6, in <module>
    from .app import Quart
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/quart/app.py", line 37, in <module>
    from .asgi import ASGIHTTPConnection, ASGILifespan, ASGIWebsocketConnection
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/quart/asgi.py", line 11, in <module>
    from .debug import traceback_response
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/quart/debug.py", line 8, in <module>
    from .wrappers import Response
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/quart/wrappers/__init__.py", line 3, in <module>
    from .base import BaseRequestWebsocket, JSONMixin
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/quart/wrappers/base.py", line 38, in <module>
    from werkzeug.useragents import UserAgent
ModuleNotFoundError: No module named 'werkzeug.useragents'
```

**Comment by MingxuanGame** [comment]
`werkzeug`也需要降版本
```bash
pip install werkzeug==2.0.3
```

**Comment by 2270057439** [comment]
> ```shell
> pip install werkzeug==2.0.3
> ```

有用 🙏

**Comment by cleoold** [comment]
```sh
pip uninstall nonebot
pip install nonebot
pip uninstall quart
pip install quart
```

我剛剛試了升級 quart 到最新版本，就沒有錯誤了。要不樓主再試一試？

**Comment by 2270057439** [comment]
> ```shell
> ```shell
> pip uninstall nonebot
> pip install nonebot
> pip uninstall quart
> pip install quart
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> 我剛剛試了升級 quart 到最新版本，就沒有錯誤了。要不樓主再試一試？
> ```


确实没错误了 🙏

**Comment by cleoold** [comment]
Updated aiocqhttp
