### ISSUE TITLE
ImportError: cannot import name 'overrides' from 'nonebot.typing'

### ISSUE THREAD

**Issue by ChristopherGuyan1997** [nonebot/nonebot#298]
Traceback (most recent call last):
  File "/Users/christopher/PycharmProjects/shenlan/AI_art/AI模仿声音/1.py", line 17, in <module>
    from nonebot_mockingbird_plugin import MockingBird, Params, part
  File "/Users/christopher/opt/anaconda3/envs/mockingbird2/lib/python3.9/site-packages/nonebot_mockingbird_plugin/__init__.py", line 6, in <module>
    from nonebot import export, on_command
  File "/Users/christopher/opt/anaconda3/envs/mockingbird2/lib/python3.9/site-packages/nonebot/__init__.py", line 140, in <module>
    from .command import CommandSession, CommandGroup
  File "/Users/christopher/opt/anaconda3/envs/mockingbird2/lib/python3.9/site-packages/nonebot/command/__init__.py", line 930, in <module>
    from nonebot.command.group import CommandGroup
  File "/Users/christopher/opt/anaconda3/envs/mockingbird2/lib/python3.9/site-packages/nonebot/command/group.py", line 3, in <module>
    from nonebot.plugin import on_command
  File "/Users/christopher/opt/anaconda3/envs/mockingbird2/lib/python3.9/site-packages/nonebot/plugin/__init__.py", line 46, in <module>
    from .on import on as on
  File "/Users/christopher/opt/anaconda3/envs/mockingbird2/lib/python3.9/site-packages/nonebot/plugin/on.py", line 13, in <module>
    from nonebot.matcher import Matcher
  File "/Users/christopher/opt/anaconda3/envs/mockingbird2/lib/python3.9/site-packages/nonebot/matcher.py", line 8, in <module>
    from nonebot.internal.matcher import Matcher as Matcher
  File "/Users/christopher/opt/anaconda3/envs/mockingbird2/lib/python3.9/site-packages/nonebot/internal/matcher.py", line 20, in <module>
    from nonebot.dependencies import Dependent
  File "/Users/christopher/opt/anaconda3/envs/mockingbird2/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 18, in <module>
    from nonebot.utils import run_sync, is_coroutine_callable
  File "/Users/christopher/opt/anaconda3/envs/mockingbird2/lib/python3.9/site-packages/nonebot/utils.py", line 32, in <module>
    from nonebot.typing import overrides
ImportError: cannot import name 'overrides' from 'nonebot.typing' 

在运行这个项目时，python=1.8+
https://github.com/Diaosi1111/nonebot_mockingbird_plugin

**Comment by yanyongyu** [comment]
不要混装nonebot1和nonebot2
